# Generated by Django 4.0.3 on 2022-04-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bodyPart', models.CharField(max_length=64)),
                ('gifUrl', models.ImageField(upload_to=None, verbose_name='')),
                ('PRreps', models.CharField(max_length=100)),
                ('PRsets', models.CharField(max_length=55)),
                ('PRweight', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=64)),
                ('finished_workout', models.BooleanField(default=False)),
                ('workoutList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutplans', to='final_proj_app.workoutlist')),
            ],
        ),
    ]
