# Generated by Django 4.0.3 on 2022-04-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_proj_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='gifUrl',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workoutList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='final_proj_app.workoutlist'),
        ),
    ]
