# Generated by Django 4.0.3 on 2022-04-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_proj_app', '0002_alter_workout_gifurl_alter_workout_workoutlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlist',
            name='userLists',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
