# Generated by Django 4.0.3 on 2022-04-24 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_proj_app', '0003_workoutlist_userlists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='name',
            new_name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutlist',
            name='userLists',
        ),
        migrations.AddField(
            model_name='workoutlist',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workoutLists', to=settings.AUTH_USER_MODEL),
        ),
    ]
