# Generated by Django 4.0.3 on 2022-04-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_proj_app', '0005_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
