# Generated by Django 4.0.3 on 2022-04-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_proj_app', '0006_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='equipment',
            field=models.CharField(default='cable', max_length=90, null=True),
        ),
    ]
